version: '1'
services:
  mariadb:
    image: mariadb:11
    container_name: my-mariadb-container
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3001:3306"

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-container
    depends_on:
      - mariadb
    ports:
      - "3000:8081"
    volumes:
      - ./:/app